apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
<<<<<<< Updated upstream
    - image: nightcrawler086/auth
=======
    - image: localhost:5000/auth
>>>>>>> Stashed changes
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .